# Generated by Django 4.1.7 on 2023-03-03 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zip_codes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('zone_type', models.CharField(max_length=120)),
                ('settlement_type', models.CharField(max_length=120)),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip_codes.zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('zip_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zip_codes.zipcode')),
            ],
        ),
        migrations.CreateModel(
            name='FederalEntity',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=120, null=True)),
                ('zip_code', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='zip_codes.zipcode')),
            ],
        ),
    ]
