# Generated by Django 4.1.7 on 2023-03-05 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zip_codes', '0002_settlement_municipality_federalentity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipality',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='settlement',
            name='zip_code',
        ),
        migrations.DeleteModel(
            name='FederalEntity',
        ),
        migrations.DeleteModel(
            name='Municipality',
        ),
        migrations.DeleteModel(
            name='Settlement',
        ),
        migrations.DeleteModel(
            name='ZipCode',
        ),
    ]
