# Generated by Django 4.1.7 on 2023-03-05 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('zip_codes', '0003_remove_municipality_zip_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FederalEntity',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, max_length=120, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='ZipCode',
            fields=[
                ('zip_code', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('locality', models.CharField(max_length=120)),
                ('federal_entity_fk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zip_codes.federalentity')),
                ('municipality_fk', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zip_codes.municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('zone_type', models.CharField(max_length=120)),
                ('settlement_type', models.CharField(max_length=120)),
                ('zip_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zip_codes.zipcode')),
            ],
        ),
    ]
