# Generated by Django 4.1.7 on 2023-03-05 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip_codes', '0005_alter_municipality_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='local_key',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
