# Generated by Django 4.1.7 on 2023-03-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip_codes', '0007_alter_zipcode_federal_entity_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settlement',
            name='settlement_local_key',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
