# Generated by Django 4.1.7 on 2023-03-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zip_codes', '0008_settlement_settlement_local_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settlement',
            name='key',
            field=models.CharField(max_length=120, primary_key=True, serialize=False),
        ),
    ]
